name: flutter_custom_theme
description: Make your own custom theme for custom components. Easily share it between projects and customize.
version: 0.1.1+1
homepage: https://github.com/Innim/flutter_custom_theme
repository: https://github.com/Innim/flutter_custom_theme
issue_tracker: https://github.com/Innim/flutter_custom_theme/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  list_ext: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
