name: flutter_custom_theme
description: Make your own custom theme for custom components. Easily share it between projects and customize.
version: 0.1.0
homepage: https://github.com/innim/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  list_ext: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
